### ISSUE TITLE
Unmarshal function

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iso-bib-item#1]
The BibliographicItem and IsoBibliographicItem class has a marshaller, to.xml(). 

It also needs an unmarshalling function: I need to be able to read entries from a cache that are in a serialisation, and convert them to the IsoBibliographicItem class. This is to meet the requirements of https://github.com/riboseinc/relaton/issues/1: 

````
x = Relaton.fetch("ISO19011")
=> <# Relaton::Iso @docidentifier: "ISO 19011:2011" ... >

x.to_xml
=> <bib-item ...>

Relaton::Database.load(:local, doc_identifier: "ISO19011").to_xml / to_bibtex / to_rfcxml ...
````

If the ISO19011 is fetched from a local cache instead of the web site, I need to convert it from the serialisation back to the IsoBibliographicItem class, before converting it on to BibTex or anything else.

I'm quite happy for that serialisation to be XML, in which case the unmarshalling is simply a series of Nokogiri .at queries. So:

````
def from_xml(xmldoc)
        xml = Nokogiri::XML(xmldoc)
        IsoBibItem::IsoBibliographicItem.new(
          docid:        xml&.at("./docidentifier")&.text,
          edition:     xml&.at("./edition")&.text,
         ....
        )
end
````

**Comment by opoudjis** [comment]
The skeleton of the function is in lib/iso_bib_item/from_xml.rb

**Comment by andrew2net** [comment]
@opoudjis is the task for me?

**Comment by andrew2net** [comment]
@opoudjis if Relation store documents in JSON format then wouldn't it be easier to create BibliographicItem from JSON instead of XML?

**Comment by opoudjis** [comment]
I leave the decision to you.

**Comment by opoudjis** [comment]
And yes, @andrew2net, this task is for you.

**Comment by opoudjis** [comment]
I'll add also that while the cache is in JSON now, it might later turn into a local key/value database (as Ronald wants to be able to modify individual entries). So again, not seeing a strong argument to make serialisation be in JSON.

**Comment by opoudjis** [comment]
we're going to have to subclass the behaviour by standards type. If the standard is ISO, it will be broken up into three parts like that. If the standard is not ISO, we will expect it to be a single string.

**Comment by andrew2net** [comment]
@opoudjis why do we need to inherit `IsoProjectGroup` form `Organization` class? As I understand `IsoProjectGroup` serialized to `editorialgroup` element. But we don't serialize any data from `Organization`. So we can't recreate `Organization` from XML.
```
editorialgroup = element editorialgroup {
  technical-committee, subcommittee?, workgroup?, secretariat?
}

technical-committee =
  element technical-committee { IsoWorkgroup }

subcommittee =
  element subcommittee { IsoWorkgroup }

workgroup =
  element workgroup { IsoWorkgroup }

IsoWorkgroup =
    attribute number { xsd:int }?,
    attribute type { text }?,
    text
```

**Comment by opoudjis** [comment]
Inheritance in the UML diagrams is somewhat abused; it's actually an override operation. While conceptually the editorial group is a suborganization of ISO, in the serialisation there is no mention of the organization, nor does there need to be. So you can ignore that inheritance for the purposes of serialisation: it won't be populated.

**Comment by opoudjis** [comment]
@andrew2net Could you please prioritise this task now? It's required for further work on relaton.

**Comment by andrew2net** [comment]
@opoudjis working on it right now, suppose to finish today

**Comment by andrew2net** [comment]
@opoudjis done. I'm ready for next task

**Comment by opoudjis** [comment]
Thank you!
