### ISSUE TITLE
Subpart

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/iso-bib-item#3]
@opoudjis Do we need to add `subpart` attribute to `project-number` element to be able using iso-bib-item in Iecbib https://github.com/riboseinc/iecbib/issues/1 ?

**Comment by opoudjis** [comment]
project-number and subpart are both attributes, but yes, `subpart` has to be passed in as a parameter if `part` is.

The processing of document identifiers has radically changed, as you'll see from isobib. Just treat `subpart` the same way that gem treats `part`.
