### ISSUE TITLE
Regexp Match Issue In Ruby < 2.4

### ISSUE THREAD

**Issue by abunashir** [riboseinc/iso-bib-item#5]
Hi, I just came across this issue in one of our gem and looks like we are using some feature that was introduced on Ruby 2.4, and that's why that test suite was failing on Ruby 2.3.

<img width="914" alt="screenshot 2018-11-09 16 28 16" src="https://user-images.githubusercontent.com/1220911/48271623-07cfd880-e43d-11e8-9983-6c82d65ab157.png">

So, my question is do we want to support the older ruby versions? (ruby < 2.4) if yes, then maybe we can check if the method is defined and then try to apply that?

If not then maybe we can set the minimum version requirement for the gem that way user's know it won't work before a specific ruby version.

**Comment by opoudjis** [comment]
The agreement was indeed that we support Ruby 2.3 up, and I'm really surprised that this has slipped through Travis. I'll patch it, the `match?` operator can usually be replaced with `match`.

**Comment by opoudjis** [comment]
@andrew2net, this did not get picked up in Rspec testing, and Rspec testing should be exploring all branches of code, not just one example.

**Comment by skalee** [comment]
@opoudjis It's worth to update Ruby version here as well, otherwise Hound may complain that you don't use `#match?`:

https://github.com/riboseinc/iso-bib-item/blob/570314fede9215add21eb7db8c87dcc31089c012/.rubocop.yml#L1-L2

**Comment by opoudjis** [comment]
@skalee  I will change the TargetRubyVersion values for the 25 gems I maintain; but given that the last time I had any time to run Rubocop on any of them was 6 months ago, I doubt it does much good.

**Comment by abunashir** [comment]
Thanks @opoudjis, amazing work! Lets also make our test suite cover this edge cases.

**Comment by skalee** [comment]
@opoudjis I thought these repos have Hound CI enabled. If yes, then wrong target Ruby version may result with misleading messages (for instance, one check suggests using `#match?` in situations like this). If no, then indeed it's less important.

**Comment by opoudjis** [comment]
@skalee I've checked, and of my 28 gems, just 9 have hound.yml. They almost all have Rubocop; I think the instruction to have Hound was not explicit when I joined 

@abunashir Welp, when I write testing, I am guided by the coverage tool :-) , so at least the gems I've authored should be mostly ok. Will discuss with @ronaldtse who should be writing the testing for the relaton suite.

**Comment by skalee** [comment]
I only wanted to say that if some repository has Hound enabled or intensively uses Rubocop in any other way, then `TargetRubyVersion` in `.rubocop.yml` is important.

**Comment by ronaldtse** [comment]
Thanks guys!
