### ISSUE TITLE
Improved rspec coverage

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iso-bib-item#6]
#5 happened because rspec did not adequately test the code. rspec should be testing *all* branches of the code, and you should be confirming this using the coverage tool. xml_parser.rb in this gem, for example, has 19 lines uncovered by rspec, and the line that did not work under Ruby 2.3 was one of them.

Please update rspec testing throughout the relaton suite of gems to improve coverage of unit testing.

**Comment by andrew2net** [comment]
Ok, will do it at the end of the week.

**Comment by andrew2net** [comment]
@opoudjis made the gem 100% covered

**Comment by opoudjis** [comment]
Thank you!
